# Generated by Django 5.0 on 2023-12-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Publish"),
                    ("D", "Draft"),
                    ("PR", "Private"),
                    ("T", "Trash"),
                ],
                default="D",
                max_length=2,
            ),
        ),
    ]
