# Generated by Django 5.0 on 2023-12-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_projectitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectitem",
            name="html_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
