# Generated by Django 5.0 on 2023-12-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_projectitem_html_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectitem",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="projectitem",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
