# Generated by Django 5.0 on 2023-12-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_projectitem_name_alter_projectitem_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectitem",
            name="test",
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
