# Generated by Django 5.0 on 2023-12-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_projectitem_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="mediatype",
            table="portfolio_project_media_type",
        ),
    ]
