# Generated by Django 5.0 on 2023-12-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_alter_mediatype_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="mediatype",
            table="portfolio_media_type",
        ),
    ]
