# Generated by Django 5.0 on 2023-12-13 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_mediatype_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectitem",
            name="item_order",
            field=models.IntegerField(
                blank=True,
                help_text="Enter the project item order",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
