# Generated by Django 5.0 on 2023-12-18 20:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_remove_projectitem_image_lg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                (
                    "thumbnail",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                (
                    "medium",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                (
                    "medium_large",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                (
                    "large",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                (
                    "admin_list_thumb",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.projectitem",
                    ),
                ),
            ],
        ),
    ]
