# Generated by Django 5.0 on 2023-12-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_rename_is_visible_projectitemattachment_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectitemattachment",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
