# Generated by Django 5.0 on 2023-12-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_alter_projectitemimage_large_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectitemimage",
            name="admin_list_thumb",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="projectitemimage",
            name="large",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="projectitemimage",
            name="medium",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="projectitemimage",
            name="medium_large",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="projectitemimage",
            name="original",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="projectitemimage",
            name="thumbnail",
            field=models.CharField(max_length=200),
        ),
    ]
