# Generated by Django 5.0 on 2023-12-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_alter_projectitemimage_admin_list_thumb_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Check if the client should be visible"
            ),
        ),
        migrations.AlterField(
            model_name="industry",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Check if the industry should be visible"
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Check if the market should be visible"
            ),
        ),
        migrations.AlterField(
            model_name="mediatype",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Check if the media type should be visible"
            ),
        ),
        migrations.AlterField(
            model_name="projectitemattachment",
            name="visible",
            field=models.BooleanField(
                default=True,
                help_text="Check if the project item attachment should be visible",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Check if the role should be visible"
            ),
        ),
    ]
