# Generated by Django 5.0.1 on 2024-01-27 21:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0027_projectitem_media_type_alter_project_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="client",
        ),
        migrations.RemoveField(
            model_name="project",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="project",
            name="market",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mediatype",
        ),
        migrations.RemoveField(
            model_name="project",
            name="role",
        ),
        migrations.RemoveField(
            model_name="project",
            name="year",
        ),
        migrations.AddField(
            model_name="projectitem",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_items",
                related_query_name="project_item",
                to="portfolio.client",
            ),
        ),
        migrations.AddField(
            model_name="projectitem",
            name="industry",
            field=models.ManyToManyField(
                blank=True,
                related_name="project_items",
                related_query_name="project_item",
                to="portfolio.industry",
            ),
        ),
        migrations.AddField(
            model_name="projectitem",
            name="market",
            field=models.ManyToManyField(
                blank=True,
                related_name="project_items",
                related_query_name="project_item",
                to="portfolio.market",
            ),
        ),
        migrations.AddField(
            model_name="projectitem",
            name="role",
            field=models.ManyToManyField(
                blank=True,
                related_name="project_items",
                related_query_name="project_item",
                to="portfolio.role",
            ),
        ),
        migrations.AddField(
            model_name="projectitem",
            name="year",
            field=models.IntegerField(
                blank=True,
                help_text="Enter the project year as a 4-digit number",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
        migrations.RemoveField(
            model_name="projectitem",
            name="media_type",
        ),
        migrations.AddField(
            model_name="projectitem",
            name="media_type",
            field=models.ManyToManyField(
                blank=True,
                related_name="project_items",
                related_query_name="project_item",
                to="portfolio.mediatype",
            ),
        ),
    ]
